### ISSUE TITLE
Reverse converting all struct payloads to atom keys

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smart_city_data#19]
"As a maintainer of the SCOS
 
  I want my application to use resources wisely
 
  So that it can perform well with minimal oversight
 
 smart_city_data is currently converting the entire contents of a struct to use atom keys. This risks overflowing the atom table of the BEAM on the apps that parse data and datasets into structs which would cause the apps to crash.
 
 
 
 Refactor the library to only convert the top level keys and not recursively create atom keys in message payloads
 
 
 
 Review each micro service and generate additional cards for each application that needs updating.
 
 
 
 Tech Note:¬†[https://github.com/SmartColumbusOS/smart_city_data/blob/master/lib/smart_city/data.ex#L45]
 
 06/27/19 - Migrated from SMRT-1380"

**Comment by jeffgrunewald** [comment]
Completed: https://github.com/smartcitiesdata/smart_city_data/pull/21
